INSERT INTO codpais VALUES (000,"N�o Definido");
INSERT INTO codpais VALUES (013,"Afeganist�o");
INSERT INTO codpais VALUES (015,"Aland, Ilhas");
INSERT INTO codpais VALUES (017,"Alb�nia");
INSERT INTO codpais VALUES (020,"Alboran-Perejil, Ilhas");
INSERT INTO codpais VALUES (023,"Alemanha");
INSERT INTO codpais VALUES (025,"Alemanha Oriental");
INSERT INTO codpais VALUES (031,"Burkina Faso");
INSERT INTO codpais VALUES (037,"Andorra");
INSERT INTO codpais VALUES (040,"Angola");
INSERT INTO codpais VALUES (041,"Anguilla");
INSERT INTO codpais VALUES (042,"Ant�rtica");
INSERT INTO codpais VALUES (043,"Ant�gua e Barbuda");
INSERT INTO codpais VALUES (047,"Antilhas Holandesas");
INSERT INTO codpais VALUES (053,"Ar�bia Saudita");
INSERT INTO codpais VALUES (059,"Arg�lia");
INSERT INTO codpais VALUES (063,"Argentina");
INSERT INTO codpais VALUES (064,"Arm�nia");
INSERT INTO codpais VALUES (065,"Aruba");
INSERT INTO codpais VALUES (069,"Austr�lia");
INSERT INTO codpais VALUES (072,"�ustria");
INSERT INTO codpais VALUES (073,"Azerbaij�o");
INSERT INTO codpais VALUES (077,"Bahamas");
INSERT INTO codpais VALUES (080,"Barein");
INSERT INTO codpais VALUES (081,"Bangladesh");
INSERT INTO codpais VALUES (083,"Barbados");
INSERT INTO codpais VALUES (085,"Belarus");
INSERT INTO codpais VALUES (087,"B�lgica");
INSERT INTO codpais VALUES (088,"Belize");
INSERT INTO codpais VALUES (090,"Bermudas");
INSERT INTO codpais VALUES (093,"Mianmar");
INSERT INTO codpais VALUES (097,"Bol�via");
INSERT INTO codpais VALUES (098,"B�snia-Herzegovina");
INSERT INTO codpais VALUES (099,"Bonaire, Saint Eustatius e Saba");
INSERT INTO codpais VALUES (100,"Interna��o na Zona Franca de Manaus");
INSERT INTO codpais VALUES (101,"Botsuana");
INSERT INTO codpais VALUES (102,"Bouvet, Ilha");
INSERT INTO codpais VALUES (105,"Brasil");
INSERT INTO codpais VALUES (108,"Brunei");
INSERT INTO codpais VALUES (111,"Bulg�ria");
INSERT INTO codpais VALUES (115,"Burundi");
INSERT INTO codpais VALUES (119,"But�o");
INSERT INTO codpais VALUES (127,"Cabo Verde");
INSERT INTO codpais VALUES (137,"Cayman, Ilhas");
INSERT INTO codpais VALUES (141,"Camboja");
INSERT INTO codpais VALUES (145,"Camar�es");
INSERT INTO codpais VALUES (149,"Canad�");
INSERT INTO codpais VALUES (150,"Canal, Ilhas do (Guernsey)");
INSERT INTO codpais VALUES (151,"Can�rias, Ilhas");
INSERT INTO codpais VALUES (152,"Canal, Ilhas do (Jersey)");
INSERT INTO codpais VALUES (153,"Cazaquist�o");
INSERT INTO codpais VALUES (154,"Catar");
INSERT INTO codpais VALUES (158,"Chile");
INSERT INTO codpais VALUES (160,"China");
INSERT INTO codpais VALUES (161,"Taiwan (Formosa)");
INSERT INTO codpais VALUES (163,"Chipre");
INSERT INTO codpais VALUES (165,"Cocos (Keeling), Ilhas");
INSERT INTO codpais VALUES (169,"Col�mbia");
INSERT INTO codpais VALUES (173,"Comores");
INSERT INTO codpais VALUES (177,"Congo");
INSERT INTO codpais VALUES (183,"Cook, Ilhas");
INSERT INTO codpais VALUES (187,"Coreia do Norte");
INSERT INTO codpais VALUES (190,"Coreia do Sul");
INSERT INTO codpais VALUES (193,"Costa do Marfim");
INSERT INTO codpais VALUES (195,"Cro�cia");
INSERT INTO codpais VALUES (196,"Costa Rica");
INSERT INTO codpais VALUES (198,"Coveite (Kuweit)");
INSERT INTO codpais VALUES (199,"Cuba");
INSERT INTO codpais VALUES (200,"Cura�ao");
INSERT INTO codpais VALUES (229,"Benin");
INSERT INTO codpais VALUES (232,"Dinamarca");
INSERT INTO codpais VALUES (235,"Dominica");
INSERT INTO codpais VALUES (237,"Dubai");
INSERT INTO codpais VALUES (239,"Equador");
INSERT INTO codpais VALUES (240,"Egito");
INSERT INTO codpais VALUES (243,"Eritreia");
INSERT INTO codpais VALUES (244,"Emirados �rabes Unidos");
INSERT INTO codpais VALUES (245,"Espanha");
INSERT INTO codpais VALUES (246,"Eslov�nia");
INSERT INTO codpais VALUES (247,"Eslov�quia");
INSERT INTO codpais VALUES (249,"Estados Unidos");
INSERT INTO codpais VALUES (251,"Est�nia");
INSERT INTO codpais VALUES (253,"Eti�pia");
INSERT INTO codpais VALUES (255,"Falkland (Malvinas)");
INSERT INTO codpais VALUES (259,"Faroe, Ilhas");
INSERT INTO codpais VALUES (267,"Filipinas");
INSERT INTO codpais VALUES (271,"Finl�ndia");
INSERT INTO codpais VALUES (275,"Fran�a");
INSERT INTO codpais VALUES (281,"Gab�o");
INSERT INTO codpais VALUES (285,"G�mbia");
INSERT INTO codpais VALUES (289,"Gana");
INSERT INTO codpais VALUES (291,"Ge�rgia");
INSERT INTO codpais VALUES (292,"Ge�rgia do Sul e Sandwich do Sul, Ilhas");
INSERT INTO codpais VALUES (293,"Gibraltar");
INSERT INTO codpais VALUES (297,"Granada");
INSERT INTO codpais VALUES (301,"Gr�cia");
INSERT INTO codpais VALUES (305,"Groenl�ndia");
INSERT INTO codpais VALUES (309,"Guadalupe");
INSERT INTO codpais VALUES (313,"Guam");
INSERT INTO codpais VALUES (317,"Guatemala");
INSERT INTO codpais VALUES (321,"Guernsey");
INSERT INTO codpais VALUES (325,"Guiana Francesa");
INSERT INTO codpais VALUES (329,"Guin�");
INSERT INTO codpais VALUES (331,"Guin� Equatorial");
INSERT INTO codpais VALUES (334,"Guin�-Bissau");
INSERT INTO codpais VALUES (337,"Guiana");
INSERT INTO codpais VALUES (341,"Haiti");
INSERT INTO codpais VALUES (343,"Heard e ilhas mcdonald, Ilha");
INSERT INTO codpais VALUES (345,"Honduras");
INSERT INTO codpais VALUES (351,"Hong Kong");
INSERT INTO codpais VALUES (355,"Hungria");
INSERT INTO codpais VALUES (357,"I�men");
INSERT INTO codpais VALUES (358,"I�men Democr�tico");
INSERT INTO codpais VALUES (359,"Ilha de Man");
INSERT INTO codpais VALUES (361,"�ndia");
INSERT INTO codpais VALUES (365,"Indon�sia");
INSERT INTO codpais VALUES (367,"Inglaterra");
INSERT INTO codpais VALUES (369,"Iraque");
INSERT INTO codpais VALUES (372,"Ir�");
INSERT INTO codpais VALUES (375,"Irlanda");
INSERT INTO codpais VALUES (379,"Isl�ndia");
INSERT INTO codpais VALUES (383,"Israel");
INSERT INTO codpais VALUES (386,"It�lia");
INSERT INTO codpais VALUES (388,"Iugosl�via");
INSERT INTO codpais VALUES (391,"Jamaica");
INSERT INTO codpais VALUES (393,"Jersey");
INSERT INTO codpais VALUES (396,"Johnston, Ilhas");
INSERT INTO codpais VALUES (399,"Jap�o");
INSERT INTO codpais VALUES (403,"Jord�nia");
INSERT INTO codpais VALUES (411,"Kiribati");
INSERT INTO codpais VALUES (420,"Laos");
INSERT INTO codpais VALUES (423,"Lebuan, Ilhas");
INSERT INTO codpais VALUES (426,"Lesoto");
INSERT INTO codpais VALUES (427,"Let�nia");
INSERT INTO codpais VALUES (431,"L�bano");
INSERT INTO codpais VALUES (434,"Lib�ria");
INSERT INTO codpais VALUES (438,"L�bia");
INSERT INTO codpais VALUES (440,"Liechtenstein");
INSERT INTO codpais VALUES (442,"Litu�nia");
INSERT INTO codpais VALUES (445,"Luxemburgo");
INSERT INTO codpais VALUES (447,"Macau");
INSERT INTO codpais VALUES (449,"Maced�nia");
INSERT INTO codpais VALUES (450,"Madagascar");
INSERT INTO codpais VALUES (452,"Madeira, Ilha da");
INSERT INTO codpais VALUES (455,"Mal�sia");
INSERT INTO codpais VALUES (458,"Malavi");
INSERT INTO codpais VALUES (461,"Maldivas");
INSERT INTO codpais VALUES (464,"Mali");
INSERT INTO codpais VALUES (467,"Malta");
INSERT INTO codpais VALUES (472,"Marianas do Norte, Ilhas");
INSERT INTO codpais VALUES (474,"Marrocos");
INSERT INTO codpais VALUES (476,"Marshall, Ilhas");
INSERT INTO codpais VALUES (477,"Martinica");
INSERT INTO codpais VALUES (485,"Maur�cio");
INSERT INTO codpais VALUES (488,"Maurit�nia");
INSERT INTO codpais VALUES (489,"Mayotte");
INSERT INTO codpais VALUES (490,"Midway, Ilhas");
INSERT INTO codpais VALUES (493,"M�xico");
INSERT INTO codpais VALUES (494,"Mold�via");
INSERT INTO codpais VALUES (495,"M�naco");
INSERT INTO codpais VALUES (497,"Mong�lia");
INSERT INTO codpais VALUES (498,"Montenegro");
INSERT INTO codpais VALUES (499,"Micron�sia");
INSERT INTO codpais VALUES (501,"Montserrat");
INSERT INTO codpais VALUES (505,"Mo�ambique");
INSERT INTO codpais VALUES (507,"Nam�bia");
INSERT INTO codpais VALUES (508,"Nauru");
INSERT INTO codpais VALUES (511,"Christmas (Navidad), Ilha");
INSERT INTO codpais VALUES (517,"Nepal");
INSERT INTO codpais VALUES (521,"Nicar�gua");
INSERT INTO codpais VALUES (525,"N�ger");
INSERT INTO codpais VALUES (528,"Nig�ria");
INSERT INTO codpais VALUES (531,"Niue");
INSERT INTO codpais VALUES (535,"Norfolk, Ilha");
INSERT INTO codpais VALUES (538,"Noruega");
INSERT INTO codpais VALUES (542,"Nova Caled�nia");
INSERT INTO codpais VALUES (545,"Papua Nova Guin�");
INSERT INTO codpais VALUES (548,"Nova Zel�ndia");
INSERT INTO codpais VALUES (551,"Vanuatu");
INSERT INTO codpais VALUES (556,"Om�");
INSERT INTO codpais VALUES (563,"Pac�fico, Ilhas do (Administra��o dos EUA)");
INSERT INTO codpais VALUES (566,"Pac�fico, Ilhas do (EUA)");
INSERT INTO codpais VALUES (569,"Pac�fico, Ilhas do (Territ�rio Fideicomisso EUA)");
INSERT INTO codpais VALUES (573,"Pa�ses Baixos (Holanda)");
INSERT INTO codpais VALUES (575,"Palau");
INSERT INTO codpais VALUES (576,"Paquist�o");
INSERT INTO codpais VALUES (578,"Palestina");
INSERT INTO codpais VALUES (580,"Panam�");
INSERT INTO codpais VALUES (583,"Papua, Territ�rio de");
INSERT INTO codpais VALUES (586,"Paraguai");
INSERT INTO codpais VALUES (589,"Peru");
INSERT INTO codpais VALUES (593,"Pitcairn");
INSERT INTO codpais VALUES (599,"Polin�sia Francesa");
INSERT INTO codpais VALUES (603,"Pol�nia");
INSERT INTO codpais VALUES (607,"Portugal");
INSERT INTO codpais VALUES (611,"Porto Rico");
INSERT INTO codpais VALUES (623,"Qu�nia");
INSERT INTO codpais VALUES (625,"Quirguist�o");
INSERT INTO codpais VALUES (628,"Reino Unido");
INSERT INTO codpais VALUES (640,"Rep�blica Centro-Africana");
INSERT INTO codpais VALUES (647,"Rep�blica Dominicana");
INSERT INTO codpais VALUES (660,"Reuni�o");
INSERT INTO codpais VALUES (665,"Zimb�bue");
INSERT INTO codpais VALUES (670,"Rom�nia");
INSERT INTO codpais VALUES (675,"Ruanda");
INSERT INTO codpais VALUES (676,"R�ssia");
INSERT INTO codpais VALUES (677,"Salom�o, Ilhas");
INSERT INTO codpais VALUES (678,"Saint Kitts e Nevis");
INSERT INTO codpais VALUES (685,"Saara Ocidental");
INSERT INTO codpais VALUES (687,"El Salvador");
INSERT INTO codpais VALUES (690,"Samoa");
INSERT INTO codpais VALUES (691,"Samoa Americana");
INSERT INTO codpais VALUES (693,"S�o Bartolomeu");
INSERT INTO codpais VALUES (695,"S�o Crist�v�o e N�vis");
INSERT INTO codpais VALUES (697,"San Marino");
INSERT INTO codpais VALUES (698,"S�o Martinho, Ilha de (parte francesa)");
INSERT INTO codpais VALUES (699,"Sint Maarten");
INSERT INTO codpais VALUES (700,"S�o Pedro e Miquelon");
INSERT INTO codpais VALUES (705,"S�o Vicente e Granadinas");
INSERT INTO codpais VALUES (710,"Santa Helena");
INSERT INTO codpais VALUES (715,"Santa L�cia");
INSERT INTO codpais VALUES (720,"S�o Tom� e Pr�ncipe");
INSERT INTO codpais VALUES (728,"Senegal");
INSERT INTO codpais VALUES (731,"Seicheles");
INSERT INTO codpais VALUES (735,"Serra Leoa");
INSERT INTO codpais VALUES (737,"S�rvia");
INSERT INTO codpais VALUES (741,"Singapura");
INSERT INTO codpais VALUES (744,"S�ria");
INSERT INTO codpais VALUES (748,"Som�lia");
INSERT INTO codpais VALUES (750,"Sri Lanka");
INSERT INTO codpais VALUES (754,"Suazil�ndia");
INSERT INTO codpais VALUES (755,"Svalbard e Jan Mayen");
INSERT INTO codpais VALUES (756,"�frica do Sul");
INSERT INTO codpais VALUES (759,"Sud�o");
INSERT INTO codpais VALUES (760,"Sud�o do Sul");
INSERT INTO codpais VALUES (764,"Su�cia");
INSERT INTO codpais VALUES (767,"Su��a");
INSERT INTO codpais VALUES (770,"Suriname");
INSERT INTO codpais VALUES (772,"Tadjiquist�o");
INSERT INTO codpais VALUES (776,"Tail�ndia");
INSERT INTO codpais VALUES (780,"Tanz�nia");
INSERT INTO codpais VALUES (781,"Terras Austrais Francesas");
INSERT INTO codpais VALUES (782,"Territ�rio Brit�nico do Oceano �ndico");
INSERT INTO codpais VALUES (783,"Djibuti");
INSERT INTO codpais VALUES (785,"Territ�rio da Alta Comiss�o do Pac�fico Ocidental");
INSERT INTO codpais VALUES (786,"Territ�rio Ant�rtico Brit�nico");
INSERT INTO codpais VALUES (788,"Chade");
INSERT INTO codpais VALUES (790,"Tchecoslov�quia");
INSERT INTO codpais VALUES (791,"Tcheca, Rep�blica");
INSERT INTO codpais VALUES (795,"Timor Leste");
INSERT INTO codpais VALUES (800,"Togo");
INSERT INTO codpais VALUES (805,"Toquelau");
INSERT INTO codpais VALUES (810,"Tonga");
INSERT INTO codpais VALUES (815,"Trinidad e Tobago");
INSERT INTO codpais VALUES (820,"Tun�sia");
INSERT INTO codpais VALUES (823,"Turcas e Caicos, Ilhas");
INSERT INTO codpais VALUES (824,"Turcomenist�o");
INSERT INTO codpais VALUES (827,"Turquia");
INSERT INTO codpais VALUES (828,"Tuvalu");
INSERT INTO codpais VALUES (831,"Ucr�nia");
INSERT INTO codpais VALUES (833,"Uganda");
INSERT INTO codpais VALUES (840,"Uni�o das Rep�blicas Socialistas Sovi�ticas");
INSERT INTO codpais VALUES (845,"Uruguai");
INSERT INTO codpais VALUES (847,"Uzbequist�o");
INSERT INTO codpais VALUES (848,"Vaticano");
INSERT INTO codpais VALUES (850,"Venezuela");
INSERT INTO codpais VALUES (858,"Vietn�");
INSERT INTO codpais VALUES (863,"Virgens, Ilhas (Brit�nicas)");
INSERT INTO codpais VALUES (866,"Virgens, Ilhas (Americanas)");
INSERT INTO codpais VALUES (870,"Fiji");
INSERT INTO codpais VALUES (873,"Wake, Ilha");
INSERT INTO codpais VALUES (875,"Wallis e Futuna, Ilhas");
INSERT INTO codpais VALUES (888,"Congo, Rep�blica Democr�tica");
INSERT INTO codpais VALUES (890,"Z�mbia");
INSERT INTO codpais VALUES (895,"Zona do Canal do Panam�");
INSERT INTO codpais VALUES (990,"Provis�o de Navios e Aeronaves");
INSERT INTO codpais VALUES (994,"A Designar");
INSERT INTO codpais VALUES (995,"Bancos Centrais");
INSERT INTO codpais VALUES (997,"Organiza��es Internacionais");
INSERT INTO codpais VALUES (998,"Sem informa��o");
INSERT INTO codpais VALUES (999,"N�o Declarados");
